[package]
name = "rtd-app"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rust TODO Cli Tool."

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }


[[bin]]
name = "rtd"
path = "src/main.rs"
